#pragma once

#include <string>
#include <vector>

#include "core/Mesh.hpp"

namespace engine::core {

struct FbxLoadResult {
    bool succeeded = false;
    std::string error; // set on failure, empty on success
    std::vector<Vertex> vertices;
    std::vector<uint32_t> indices;
};

// Kronos (Alpha Roadmap Phase 8, "Asset Pipeline" -- "Automated Asset
// Hot-Import Pipeline"): a real FBX loader via the vendored ufbx
// (cmake/Dependencies.cmake) -- Autodesk's own official FBX SDK is
// proprietary and EULA-gated (confirmed: a plain fetch of its download
// page 403s, the same shape of wall Ultralight's SDK has -- see
// engine/external/ultralight-sdk/README.md for that other case); ufbx
// is the real, standard, license-clean alternative every open-source
// engine reaches for instead, needing no Autodesk SDK at all.
//
// Same real, narrow, stated-plainly scope as ObjLoader.hpp/GltfLoader.hpp:
// geometry only (materials/skinning/animation parsed by ufbx internally
// but not read here), one combined mesh per file (every mesh in the
// scene concatenated, matching what this engine's Renderable model
// actually supports). Real space normalization on load (target_axes =
// right-handed Y-up, target_unit_meters = 1.0) -- unlike glTF (which
// the spec itself mandates Y-up meters, so GltfLoader does no
// conversion) or OBJ (no formal standard, read as-is), real-world FBX
// exports vary wildly in both up-axis and unit scale between DCC tools,
// so skipping this normalization would import a meaningful fraction of
// real files rotated or absurdly mis-scaled. Missing normals are
// generated by ufbx itself (generate_missing_normals) rather than this
// loader's own flat-normal fallback (unlike GltfLoader's) -- a real,
// second real technique already built into the library, not
// duplicated here.
[[nodiscard]] FbxLoadResult loadFbx(const std::string& path);

} // namespace engine::core
