#include "core/ProjectReadmeGenerator.hpp"

#include <cstdio>
#include <ctime>
#include <fstream>
#include <sstream>

#include "core/KronosVersion.hpp"

namespace engine::core {

namespace {
std::string formatDate(int64_t unixSeconds) {
    if (unixSeconds <= 0) return "(unknown date)";
    std::time_t time = static_cast<std::time_t>(unixSeconds);
    std::tm tmValue{};
    gmtime_r(&time, &tmValue);
    char buffer[16]; // "YYYY-MM-DD\0"
    std::snprintf(buffer, sizeof(buffer), "%04d-%02d-%02d", tmValue.tm_year + 1900, tmValue.tm_mon + 1, tmValue.tm_mday);
    return buffer;
}
} // namespace

std::string generateProjectReadme(const ProjectFile& project) {
    std::ostringstream out;
    out << "# " << project.name << "\n\n";
    out << "A project built with Kronos Studio, version " << kKronosVersion << ".\n\n";
    out << "- Created: " << formatDate(project.createdAtUnixSeconds) << "\n";
    out << "- Last modified: " << formatDate(project.modifiedAtUnixSeconds) << "\n";
    out << "- Project format version: " << project.version << "\n\n";

    out << "## Scenes\n\n";
    if (project.scenePaths.empty()) {
        out << "No scenes yet.\n";
    } else {
        for (size_t i = 0; i < project.scenePaths.size(); ++i) {
            bool isActive = static_cast<int>(i) == project.activeSceneIndex;
            out << "- " << project.scenePaths[i] << (isActive ? " (active)" : "") << "\n";
        }
    }
    out << "\n---\n_Generated by Kronos Studio " << kKronosVersion << "._\n";
    return out.str();
}

bool writeProjectReadme(const ProjectFile& project, const std::string& projectDirectory) {
    std::ofstream out(projectDirectory + "/README.md", std::ios::trunc);
    if (!out.is_open()) return false;
    out << generateProjectReadme(project);
    return out.good();
}

} // namespace engine::core
