ALTER TABLE games ADD COLUMN IF NOT EXISTS project_url TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN IF NOT EXISTS manifest_url TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN IF NOT EXISTS genre TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN IF NOT EXISTS thumbnail_color TEXT NOT NULL DEFAULT '';