// Local disk fallback for Dynamic Asset Streaming: every deployment that
// never sets S3_BUCKET (see config.js's own s3Bucket comment) still gets a
// real, working package upload/download path -- backed by this process's
// own filesystem instead of a bucket -- rather than a permanent 503.
import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';

import { config } from '../config.js';

export { packageObjectKey } from './objectKey.js';

const baseDir = path.resolve(config.localStorageDir);

// Every key this module ever receives is generated by packageObjectKey()
// from a regex-validated hex sha256 (enforced in catalog/routes.js before
// it reaches here), so this can never actually see `../`-style input --
// this check is just cheap, real insurance against that invariant ever
// being loosened, not a defense against input that reaches here today.
function objectPath(key) {
  const resolved = path.resolve(baseDir, key);
  if (resolved !== baseDir && !resolved.startsWith(baseDir + path.sep)) {
    throw new Error(`Refusing to touch a local storage path outside its root: ${key}`);
  }
  return resolved;
}

export async function headObject(key) {
  try {
    const stat = await fsp.stat(objectPath(key));
    return { exists: true, sizeBytes: stat.size };
  } catch (err) {
    if (err.code === 'ENOENT') return { exists: false };
    throw err;
  }
}

// Streams an incoming request body straight to a temp file, then
// atomically renames it into place -- a headObject()/verifyObjectHash()
// call that lands mid-upload sees either the complete previous object or
// nothing, never a half-written one.
export async function writeObjectFromStream(key, readable, maxBytes) {
  const dest = objectPath(key);
  await fsp.mkdir(path.dirname(dest), { recursive: true });
  const tmp = `${dest}.${crypto.randomBytes(8).toString('hex')}.tmp`;
  const out = fs.createWriteStream(tmp);
  let sizeBytes = 0;
  try {
    for await (const chunk of readable) {
      sizeBytes += chunk.length;
      if (sizeBytes > maxBytes) {
        const err = new Error(`Upload exceeds the ${maxBytes}-byte package size limit.`);
        err.code = 'PACKAGE_TOO_LARGE';
        throw err;
      }
      if (!out.write(chunk)) await new Promise((resolve) => out.once('drain', resolve));
    }
    await new Promise((resolve, reject) => {
      out.end((err) => (err ? reject(err) : resolve()));
    });
    await fsp.rename(tmp, dest);
  } catch (err) {
    out.destroy();
    await fsp.unlink(tmp).catch(() => {});
    throw err;
  }
  return { sizeBytes };
}

// Same real, streamed, server-side re-hash s3.js's own verifyObjectHash()
// does -- never trusts the client's claimed hash, and bounded by
// config.packageMaxSizeBytes the same way (enforced up front at
// writeObjectFromStream() time, not here, so this never re-derives that
// bound against bytes already accepted onto disk).
export async function verifyObjectHash(key, expectedSha256Hex) {
  const hash = crypto.createHash('sha256');
  let sizeBytes = 0;
  for await (const chunk of fs.createReadStream(objectPath(key))) {
    sizeBytes += chunk.length;
    hash.update(chunk);
  }
  return { matches: hash.digest('hex') === expectedSha256Hex, sizeBytes };
}

export function readObjectStream(key) {
  return fs.createReadStream(objectPath(key));
}

export async function deleteObject(key) {
  await fsp.unlink(objectPath(key)).catch((err) => {
    if (err.code !== 'ENOENT') throw err;
  });
}
